name: nanopy
on: [push]
env:
  OMP_NUM_THREADS: 2
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install -Ur requirements.txt
      - name: Build Linux/MacOS
        if: runner.os != 'Windows'
        run: python setup.py build_ext -i
      - name: Build Windows
        if: runner.os == 'Windows'
        run: python setup.py build_ext -i
        env:
          USE_VC: 1
      - run: python ghtest.py
      - name: Build GPU
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install ocl-icd-opencl-dev intel-opencl-icd clinfo
          rm -rf build/
          python setup.py build_ext -i
          clinfo
        env:
          USE_GPU: 1
  aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu_latest
          githubToken: ${{ github.token }}
          install: |
            apt-get update -q -y
            apt-get install -q -y gcc python3-dev python3-pip
          run: |
            pip install -Ur requirements.txt
            python3 setup.py build_ext -i
            python3 ghtest.py

